"""comment table

Revision ID: d1c0afcff3da
Revises: 
Create Date: 2019-05-02 18:12:36.831086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c0afcff3da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commentText', sa.String(length=144), nullable=True),
    sa.Column('postID', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_commentText'), 'comment', ['commentText'], unique=False)
    op.create_index(op.f('ix_comment_user'), 'comment', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_user'), table_name='comment')
    op.drop_index(op.f('ix_comment_commentText'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
