version: '3.3'

services:

  login:
    build:
      context: ./src/login
      dockerfile: Dockerfile-dev
    volumes:
      - ./src/login/:/usr/src/app
    ports:
      - "5001:5000"
    # environment:
    #   - FLASK_ENV=development
    #   - APP_SETTINGS=config.Config
    #   - DATABASE_URL=config.Config.SQLALCHEMY_DATABASE_URI
      # - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
   # depends_on:
    #  - users-db

  
  # users-db:
  #   build:
  #     context: ./services/users/project/db
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5436:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres