"""posts table

Revision ID: 1a516103bed6
Revises: 
Create Date: 2019-03-21 16:11:13.636565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a516103bed6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postText', sa.String(length=144), nullable=True),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_postText'), 'post', ['postText'], unique=False)
    op.create_index(op.f('ix_post_user'), 'post', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_user'), table_name='post')
    op.drop_index(op.f('ix_post_postText'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
