apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notificationsocket
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: notificationsocket
    spec:
      containers:
      - name: notificationsocket
        image: jordanparezysua/notificationsocket-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: notificationsocket-service
spec:
  type: NodePort
  selector:
    app: notificationsocket
  ports:
  - port: 8889
    targetPort: 8889
    nodePort: 30512
