apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: comment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
      - name: comment
        image: jordanparezysua/comment-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: comment-service
spec:
  type: NodePort
  selector:
    app: comment
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30502
