apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: post
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post
        image: jordanparezysua/post-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  type: NodePort
  selector:
    app: post
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30501