apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cyber
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: cyber
    spec:
      containers:
      - name: cyber
        image: jordanparezysua/cyber-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cyber-service
spec:
  type: NodePort
  selector:
    app: cyber
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30504
