"""Post

Revision ID: b3117ffbe1dd
Revises: 
Create Date: 2019-05-19 21:32:17.739386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3117ffbe1dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postText', sa.String(length=144), nullable=True),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_postText'), 'post', ['postText'], unique=False)
    op.create_index(op.f('ix_post_user'), 'post', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_user'), table_name='post')
    op.drop_index(op.f('ix_post_postText'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
