apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: garden
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: garden
    spec:
      containers:
      - name: garden
        image: jordanparezysua/gardenservice
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: garden-service
spec:
  type: NodePort
  selector:
    app: garden
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
