apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chatsocket
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chatsocket
    spec:
      containers:
      - name: chatsocket
        image: jordanparezysua/chatsocket-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: chatsocket-service
spec:
  type: NodePort
  selector:
    app: chatsocket
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30511
