apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: login
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: jordanparezysua/login-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  type: NodePort
  selector:
    app: login
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
