apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: jordanparezysua/admin-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  type: NodePort
  selector:
    app: admin
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30510
