apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: advertising
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: advertising
    spec:
      containers:
      - name: advertising
        image: jordanparezysua/advertising-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: advertising-service
spec:
  type: NodePort
  selector:
    app: advertising
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30509
