apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: advertisement
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: adveertisement
    spec:
      containers:
      - name: advertisement
        image: jordanparezysua/advertisement-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: advertisement-service
spec:
  type: NodePort
  selector:
    app: advertisement
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
