"""garden table

Revision ID: 4bf57949f250
Revises: 
Create Date: 2019-05-06 14:18:47.681283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf57949f250'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vegetable', sa.String(length=20), nullable=True),
    sa.Column('fruits', sa.String(length=120), nullable=True),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.Column('Img_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('garden')
    # ### end Alembic commands ###
